#!/bin/sh
host=https://raw.github.com/bleis-tift/Git-Hooks
if [ $(git rev-parse --is-bare-repository) = "false" ]; then
    echo "please run on bare repository"
    exit 1
fi


for i in update; do
    echo $i
    curl -L -o hooks/$i $host/master/$i
    chmod a+x hooks/$i
done
